Eventify Final Project
IamYunusAli/Eventify-backend pull request #23
Opened 2023-01-18 10:58 UTC by IamYunusAli

## Eventify
In this PR we have done the following project requirements.
- [Requirementets](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md)

### Frontend 

- [Frontend Repo](https://github.com/betses/Final-capstone--frontend)
- [Live Demo](https://eventify-cap.netlify.app/)

### API 

- [Live API Endpoints Users](https://eventifyhub.herokuapp.com/users)
- [Live API Endpoints Events](https://eventifyhub.herokuapp.com/events)
- [Live API Endpoints Reserves](https://eventifyhub.herokuapp.com/reserves)

-  [API DOCS](https://eventifyhub.herokuapp.com/api-docs/)

### Team
 - @betses
 - @fullstop125 
 - @IamYunusAli

2023-01-18 13:39 UTC, Meltrust requested changes
note:  Please go to the frontend PR to view the review comments (working on it).

Hi @IamYunusAli,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  API is working well✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._

_I strongly recommend you take them into account as they can improve your final evaluation._





Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-01-18 13:39 UTC, Meltrust commented on README.md
> +```
- [ ]  You are using Rspec, but the "test" folder still exists, which is used by another test framework. Kindly consider deleting that folder if you are not using it. 👍

2023-01-18 13:39 UTC, Meltrust commented on config/routes.rb
> +  resources :reserves
## Explanation

By using the `only:` keyword parameter, you can generate only the routes that you are using.

[Look](https://launchschool.com/books/demystifying_rails/read/routes_and_resources):

![https://user-images.githubusercontent.com/57421823/201431229-f7861d5e-3462-4897-b6fa-1242581bf06f.png](https://user-images.githubusercontent.com/57421823/201431229-f7861d5e-3462-4897-b6fa-1242581bf06f.png)

## Example

```ruby
resources :users, only: [:index, :create, :show]

```

That way, your routes will be more consistent, and only the ones needed will be generated💪

2023-01-18 14:28 UTC, IamYunusAli commented on config/routes.rb
> +  resources :reserves
thank you @Meltrust I will manage to update the required changes.

2023-01-19 08:01 UTC, Meltrust approved these changes
#### Hi @IamYunusAli,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Routes have been refactored so only the necessary ones are generated✔️ 
- Test folder used by another framework has been removed✔️ 
- Excellent work, the API works well✔️ 



Cheers and Happy coding!👏👏👏


------

2023-01-19 13:20 UTC, merged